spring.application.name=sm-core
# Max file size.
spring.http.multipart.max-file-size=10Mb
# Max request size.
spring.http.multipart.max-request-size=10Mb



app.title=Meu aplicativo Spring Boot

# Tamanho maximo de fotos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Ligação BD
spring.datasource.url=jdbc:mariadb://mariadb:3306/teste
spring.datasource.username=nfoliveira
spring.datasource.password=123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.keepaliveTime=300000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000

# podes ainda usar propriedade legacy
sm.core.amb=PROD
sm.core.storage=LOCAL
# LOCAL (container)
sm.core.storage.basePath=/SM/www

spring.mail.host=mail.sm.com.pt
spring.mail.port=587
spring.mail.username=geral@sm.com.pt
spring.mail.password=z4hyXkTb2H38TWA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


sm.core.tenant_id.1.name=hcmaia
sm.core.tenant_id.2.name=advalongo
sm.core.tenant_id.3.name=cis

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB